{{- $compName := .Values.componentName -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ $compName }}
  labels:
    {{- include "watsonnlp.labels" (list . $compName) | nindent 4 }}
spec:
  #replicas: 1 is the default, let's not use it and scale manually, so that kubectl apply does not overwrite this
  selector:
    matchLabels:
      {{- include "watsonnlp.selectorLabels" (list . $compName) | nindent 6 }}
  progressDeadlineSeconds: 1800
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 1
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "watsonnlp.selectorLabels" (list . $compName) | nindent 8 }}
    spec:
      volumes:  
        - name: models
          emptyDir: {}   
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- if .Values.models }}
      initContainers:
      {{- $acceptLicense := .Values.acceptLicense }}
      {{- range $index, $model := .Values.models }}  
      {{- $registryName := $model.registry }}
      {{- $image := $model.image }}
      - name: model-{{ $index }}
        image: {{- include "watsonnlp.registries" (list $ $registryName $image) | trim | indent 1}}
        volumeMounts:
          - name: models
            mountPath: /app/models      
      {{- if (default $acceptLicense false)}}
        env:
          - name: ACCEPT_LICENSE
            value: "true"
      {{- end }}
      {{- end }}
      {{- end }}
      containers:
      - name: watson-nlp
        {{- $registryName := .Values.runtime.registry }}
        {{- $image := .Values.runtime.image }}
        image: {{- include "watsonnlp.registries" (list $ $registryName $image) | trim | indent 1}}
        ports:
          - containerPort: 8080
          - containerPort: 8085
        volumeMounts:
          - name: models
            mountPath: /app/models
        env:
          - name: LOCAL_MODELS_DIR
            value: /app/models
          - name: LOG_LEVEL
            value: debug
          {{- if (default .Values.acceptLicense false)}}
          - name: ACCEPT_LICENSE
            value: "true"
          {{- end }}
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8085"]
          initialDelaySeconds: 5
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:8085"]
          initialDelaySeconds: 10
